import { declareDiscoveryExtension } from "@x402/extensions/bazaar";

export const SERVICE = "SiteCheck";
const TOOLS = "Pay-per-call tools for AI agents: image generation, speech-to-text, text-to-speech, embeddings, LLM chat, website audits and contact enrichment, web page to Markdown reader, PDF to text, sitemap URLs, tech stack detection, translation, exchange rates, e-mail pre-check, domain RDAP/DNS lookup, Solana token checks, trending tokens and wallet holdings, plus business and compliance data (EU VAT/VIES, IBAN, LEI/GLEIF, US recalls, OSHA/EPA violations, UK insolvency notices).";
const list = (names) => names.length > 1 ? `${names.slice(0, -1).join(", ")} or ${names.at(-1)}` : names[0];
const MARKETS = " Plus prediction-market search, briefs, quotes and unsigned buy transactions, powered by Panta.";
export const about = (networks, { markets = false } = {}) => `${TOOLS}${markets ? MARKETS : ""} Payment: x402, USDC${networks.length ? ` on ${list(networks.map((n) => n.name))}` : ""}. No signup, no API key.`;

// The paid routes on this deployment: the prediction-market tools only when PANTA_API_KEY is set.
export const catalogFor = ({ markets = false } = {}) => (markets ? { ...CATALOG, ...MARKET_CATALOG } : CATALOG);

// One route per tool, with one x402 `accepts` entry per active network (see lib/networks.js).
export function buildRoutes(networks, catalog = CATALOG) {
  return Object.fromEntries(Object.entries(catalog).map(([route, t]) => [route, {
    accepts: networks.map((n) => ({ scheme: "exact", price: t.price, network: n.network, payTo: n.payTo })),
    description: t.description, mimeType: "application/json", serviceName: SERVICE, tags: t.tags,
    extensions: declareDiscoveryExtension(route.startsWith("POST ")
      ? { bodyType: "json", input: t.input, inputSchema: t.inputSchema, output: { example: t.example } }
      : { input: t.input, inputSchema: t.inputSchema, output: { example: t.example } }),
  }]));
}

const tool = (price, description, tags, input, inputSchema, example) => ({ price, description, tags, input, inputSchema, example });
const urlSchema = { properties: { url: { type: "string", description: "Website URL or domain, e.g. example.com" } }, required: ["url"] };

// Short OpenAPI summaries (catalog checkers such as Solana pay-skills require at most 63 chars, starting with a verb).
export const SUMMARIES = {
  "POST /api/image": "Generate an image from a text prompt",
  "POST /api/transcribe": "Transcribe audio to text with timestamps",
  "POST /api/tts": "Convert English text to speech (MP3)",
  "POST /api/embed": "Create multilingual text embeddings",
  "POST /api/chat": "Generate a chat completion with Llama 3.3 70B",
  "GET /api/audit": "Audit a website for accessibility, SEO and security",
  "GET /api/contacts": "Find company contacts from a domain",
  "GET /api/hiring": "Search the Hacker News Who is hiring thread",
  "GET /api/vat": "Validate an EU VAT number with VIES",
  "GET /api/iban": "Validate IBANs and split bank and account codes",
  "GET /api/lei": "Look up a legal entity and its parents in GLEIF",
  "GET /api/recalls": "Search US product recalls from FDA and CPSC",
  "GET /api/violations": "Search OSHA and EPA enforcement cases by company",
  "GET /api/uk-insolvency": "Search UK company insolvency notices",
  "GET /api/read": "Read a web page as clean Markdown",
  "GET /api/email-check": "Pre-check e-mail addresses without SMTP",
  "GET /api/domain": "Look up domain registration (RDAP) and DNS",
  "GET /api/solana/token": "Check a Solana token: market data and red flags",
  "GET /api/solana/trending": "List trending or new Solana tokens with flags",
  "GET /api/solana/wallet": "Get Solana wallet holdings with USD values",
  "GET /api/tech": "Detect the technologies a website uses",
  "POST /api/pdf": "Extract text from a PDF",
  "GET /api/fx": "Get ECB exchange rates and convert amounts",
  "GET /api/sitemap": "List the URLs in a website's sitemaps",
  "POST /api/translate": "Translate text between languages",
  "GET /api/markets": "Search Panta prediction markets",
  "GET /api/markets/brief": "Get a brief of one Panta prediction market",
  "POST /api/markets/quote": "Quote a buy on a Panta prediction market",
  "POST /api/markets/build-buy": "Build an unsigned Panta buy transaction",
  "POST /api/markets/report": "Report a signed Panta buy transaction",
};

// Price is in USD and charged in USDC on whichever network the buyer picks.
export const CATALOG = {
  "POST /api/image": tool("$0.005",
    "Generate an image from a text prompt (FLUX.1 schnell). Returns a base64 JPEG. Fast, 1024x1024.",
    ["image generation", "text-to-image", "flux", "ai", "images"], { prompt: "a red fox in the snow, photo", steps: 4 },
    { properties: { prompt: { type: "string", description: "Up to 2048 chars" }, steps: { type: "integer", description: "1-8, default 4" } }, required: ["prompt"] },
    { model: "@cf/black-forest-labs/flux-1-schnell", mime: "image/jpeg", image_base64: "/9j/4AAQ..." }),
  "POST /api/transcribe": tool("$0.01",
    "Speech-to-text with Whisper large-v3-turbo: send an https audio URL (or base64) up to 25 MB, get the transcript, language and timestamped segments.",
    ["speech-to-text", "transcription", "whisper", "audio", "stt"], { url: "https://example.com/audio.mp3" },
    { properties: { url: { type: "string", description: "https URL of an audio file (mp3, wav, m4a...)" }, audio_base64: { type: "string", description: "Alternative to url" }, language: { type: "string", description: "Optional ISO code, e.g. en" } } },
    { model: "@cf/openai/whisper-large-v3-turbo", text: "Hello and welcome...", language: "en", duration: 42.1, segments: [{ start: 0, end: 3.2, text: "Hello and welcome" }] }),
  "POST /api/tts": tool("$0.02",
    "English text-to-speech with Deepgram Aura-2: natural voices, up to 1000 chars per call. Returns base64 MP3.",
    ["text-to-speech", "tts", "voice", "audio", "speech"], { text: "Hello from your agent.", voice: "luna" },
    { properties: { text: { type: "string", description: "Up to 1000 chars" }, voice: { type: "string", description: "luna, asteria, athena, helena, hera, aurora, orion, apollo, arcas, atlas, hermes, zeus, draco, odysseus" } }, required: ["text"] },
    { model: "@cf/deepgram/aura-2-en", voice: "luna", mime: "audio/mpeg", audio_base64: "SUQzBAAAAAAA..." }),
  "POST /api/embed": tool("$0.001",
    "Multilingual text embeddings (BGE-M3, 1024 dimensions) for up to 100 texts per call. For search, RAG and clustering.",
    ["embeddings", "vector", "rag", "semantic search", "bge-m3"], { text: ["first document", "second document"] },
    { properties: { text: { description: "A string or an array of up to 100 strings" } }, required: ["text"] },
    { model: "@cf/baai/bge-m3", dimensions: 1024, embeddings: [[0.012, -0.034]] }),
  "POST /api/chat": tool("$0.004",
    "LLM chat completion with Llama 3.3 70B (fast): send messages or a prompt, up to 2048 output tokens.",
    ["llm", "chat", "llama", "text generation", "completion"], { prompt: "Summarize the benefits of x402 in two sentences.", max_tokens: 256 },
    { properties: { prompt: { type: "string" }, messages: { type: "array", description: "[{role, content}]" }, max_tokens: { type: "integer", description: "Up to 2048" }, temperature: { type: "number" } } },
    { model: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", response: "x402 lets agents pay per request...", usage: { prompt_tokens: 20, completion_tokens: 40 } }),
  "GET /api/audit": tool("$0.02",
    "Website audit in one call: WCAG 2.2 accessibility issues (European Accessibility Act) with fixes and a score, SEO basics, security headers and tech stack.",
    ["accessibility", "wcag", "seo", "audit", "website"], { url: "example.com" }, urlSchema,
    { url: "https://example.com/", accessibility: { score: 85, issues: [{ severity: "critical", rule: "image-alt", wcag: "1.1.1", count: 3, fix: "Add alt text" }] }, seo: { title: "Example" }, security: { hsts: true }, tech: ["Shopify"] }),
  "GET /api/contacts": tool("$0.01",
    "Company contact enrichment from a domain: emails (same-domain flagged), phones, social profiles, description and tech stack, read from the home, contact, about and legal pages.",
    ["enrichment", "contacts", "email", "company", "leads"], { url: "plausible.io" }, urlSchema,
    { domain: "plausible.io", name: "Plausible Analytics", emails: [{ email: "hello@plausible.io", sameDomain: true }], socials: { linkedin: "https://linkedin.com/company/plausible-analytics/" }, tech: ["Cloudflare"] }),
  "GET /api/hiring": tool("$0.01",
    "Search the current Hacker News 'Who is hiring?' thread: companies hiring, filtered by keywords and remote, with contact emails and links.",
    ["jobs", "hiring", "hacker news", "leads", "remote"], { q: "python", remote: "1", limit: "20" },
    { properties: { q: { type: "string", description: "Keywords, all must match" }, remote: { type: "string", description: "1 = remote only" }, limit: { type: "string", description: "Max results, up to 100" } } },
    { thread: { title: "Ask HN: Who is hiring? (September 2026)" }, total: 38, results: [{ company: "Acme", headline: "Acme | Backend Engineer | REMOTE", emails: ["jobs@acme.com"], url: "https://news.ycombinator.com/item?id=1" }] }),
  "GET /api/vat": tool("$0.002",
    "EU VAT number check: format and checksum are tested locally first (a malformed number is rejected with HTTP 400 and no charge), then the official VIES service answers whether it is valid, with the registered name and address where the member state discloses them. All 27 EU states plus Northern Ireland (XI). Source: European Commission VIES.",
    ["vat", "vies", "eu", "compliance", "kyb", "invoicing"], { number: "DE811907980" },
    { properties: { number: { type: "string", description: "VAT number with its 2-letter country prefix, e.g. DE811907980 (EL for Greece, XI for Northern Ireland). Spaces and dots are ignored" }, country: { type: "string", description: "Optional: country code, if the number has no prefix" } }, required: ["number"] },
    { input: "DE811907980", countryCode: "DE", vatNumber: "811907980", formatted: "DE811907980", valid: true, viesStatus: "OK", name: "Example GmbH", address: "Musterstrasse 1, 10115 Berlin", requestDate: "2026-10-07T08:52:29.570Z", checks: { format: "ok", checksum: "verified" }, source: "European Commission VIES (https://ec.europa.eu/taxation_customs/vies/)" }),
  "GET /api/iban": tool("$0.001",
    "IBAN validation with no network call: ISO 13616 length and structure for every country in the SWIFT IBAN registry, the mod-97 checksum, national check digits where a public algorithm exists (FR, ES, IT, BE, NL, NO, FI, PL, PT and the Balkan countries), and the split into bank code, branch code and account. Returns the electronic and print format. Pass ibans= for up to 50 at once. No bank name or BIC lookup (no dataset is bundled).",
    ["iban", "bank", "payments", "validation", "sepa"], { iban: "DE89 3704 0044 0532 0130 00" },
    { properties: { iban: { type: "string", description: "One IBAN. Spaces, dashes and lowercase are accepted" }, ibans: { type: "string", description: "Alternative: up to 50 IBANs, comma-separated" } } },
    { input: "DE89 3704 0044 0532 0130 00", valid: true, iban: "DE89370400440532013000", ibanPrint: "DE89 3704 0044 0532 0130 00", countryCode: "DE", country: "Germany", expectedLength: 22, nationalCheck: { status: "not-available", note: "no public national check-digit algorithm is applied for this country" }, ibanElectronic: "DE89370400440532013000", bban: "370400440532013000", bankCode: "37040044", branchCode: null, account: "0532013000", checks: { structure: "ok", length: "ok", mod97: "ok", national: "not-available" }, bankLookup: false }),
  "GET /api/lei": tool("$0.005",
    "Legal entity lookup in GLEIF by 20-character LEI or company name (best match plus up to 5 alternatives): legal name, status, jurisdiction, addresses, registration status and renewal date, direct and ultimate parent (or the reporting-exception reason), child counts with the first 10 direct children, and a one-line kycSummary. Source: GLEIF Global LEI Index (CC0).",
    ["lei", "gleif", "kyc", "kyb", "company", "compliance"], { q: "Siemens Aktiengesellschaft" },
    { properties: { q: { type: "string", description: "A 20-character LEI or a company name" } }, required: ["q"] },
    { matchedBy: "name", query: "Siemens Aktiengesellschaft", matchScore: 1, lei: "W38RGI023J3WT1HWRP32", legalName: "Siemens Aktiengesellschaft", status: "ACTIVE", jurisdiction: "DE", registration: { status: "ISSUED", initialRegistrationDate: "2012-06-06", nextRenewalDate: "2027-10-25", managingLou: "5299000J2N45DDNE4Y28" }, directParent: { relationship: "exception", reason: "NO_KNOWN_PERSON" }, ultimateParent: { relationship: "exception", reason: "NO_KNOWN_PERSON" }, children: { directCount: 459, ultimateCount: 572, direct: [{ lei: "529900YQP0HHGTCX1K98", name: "De Novo Software, LLC", jurisdiction: "US-CA", status: "ACTIVE" }], directShown: 10 }, alternatives: [{ lei: "52990021T5LVTQOGSU18", name: "Siemens Aktiengesellschaft Österreich", jurisdiction: "AT", status: "ACTIVE", matchScore: 0.69 }], kycSummary: "Active, registration issued, renewal due 2027-10-25, jurisdiction DE, ultimate parent: none reported (no known person)", source: "GLEIF Global LEI Index (CC0), https://www.gleif.org" }),
  "GET /api/recalls": tool("$0.003",
    "US product recalls in one schema from openFDA enforcement reports (food, drug, device) and CPSC: date, product, firm, reason, FDA Class I/II/III mapped to high/medium/low (CPSC severity is derived from the hazard text), distribution and states, and the official link. Filter by keyword, since date (default 30 days), source and classification; up to 100 rows.",
    ["recalls", "fda", "cpsc", "product safety", "compliance", "supply chain"], { q: "peanut", source: "fda,cpsc", since: "2026-09-01", limit: "20" },
    { properties: { q: { type: "string", description: "Keyword in the product or firm name" }, source: { type: "string", description: "fda, cpsc or fda,cpsc (default both)" }, since: { type: "string", description: "YYYY-MM-DD, default 30 days ago, at most one year back" }, classification: { type: "string", description: "Class I, Class II, Class III or high, medium, low" }, limit: { type: "string", description: "Max rows, 1-100, default 20" } } },
    { query: { q: "peanut", source: ["fda", "cpsc"], since: "2026-09-01", classification: null }, total: 1, returned: 1, results: [{ source: "fda", category: "food", id: "F-1234-2026", date: "2026-09-30", initiated: "2026-09-12", product: "Peanut butter cookies, 12 oz", firm: "Example Foods Inc.", reason: "Undeclared milk allergen", classification: "Class I", severity: "high", status: "Ongoing", distribution: "Nationwide", states: [], nationwide: true, link: "https://www.accessdata.fda.gov/scripts/ires/index.cfm?Event=99999" }], severityNote: "FDA severity maps Class I/II/III to high/medium/low. CPSC does not classify recalls: its severity is derived from the hazard text.", sources: ["openFDA enforcement reports (https://open.fda.gov)", "CPSC SaferProducts.gov Recall API (https://www.saferproducts.gov)"] }),
  "GET /api/violations": tool("$0.005",
    "US workplace and environmental enforcement cases by company, state and date: OSHA inspections with penalties (US Department of Labor API) and EPA enforcement cases (EPA ECHO), each with the official record link. Filters: company, state, since, minPenalty, source. OSHA is included only when the deployment has a DOL key; the answer says so otherwise. Public records matched by name, not a finding of guilt.",
    ["osha", "epa", "violations", "compliance", "due diligence", "enforcement"], { company: "Chevron Phillips", state: "TX", since: "2022-01-01", source: "osha,epa", limit: "20" },
    { properties: { company: { type: "string", description: "Company or establishment name (part of it is enough)" }, state: { type: "string", description: "2-letter US state code" }, since: { type: "string", description: "YYYY-MM-DD, default one year ago" }, minPenalty: { type: "string", description: "Minimum penalty in US dollars" }, source: { type: "string", description: "osha, epa or osha,epa (default both)" }, limit: { type: "string", description: "Max rows, 1-100, default 20" } } },
    { query: { company: "Chevron Phillips", state: "TX", since: "2022-01-01", minPenalty: null, sources: ["epa"] }, total: 1, returned: 1, results: [{ source: "epa", id: "HQ-2015-0001", company: "Chevron Phillips Chemical (LEAD)", facility: "PORT ARTHUR PLANT", state: "TX", city: "PORT ARTHUR", date: "2022-03-09", penalty: 3400000, currency: "USD", type: "Judicial, CAA §111, Final Order With Penalty", status: "Final Order Entered", link: "https://echo.epa.gov/enforcement-case-report?id=HQ-2015-0001" }], notes: ["OSHA is off on this deployment (DOL_API_KEY is not set): only EPA results are included."], sources: ["US EPA ECHO (https://echo.epa.gov)"], caveat: "Public enforcement records, matched by name: they show inspections and cases, not guilt or current compliance. Check the record link before relying on a row." }),
  "GET /api/uk-insolvency": tool("$0.003",
    "UK company insolvency notices (administrations, liquidations, winding-up petitions and similar) from The Gazette, read from our own nightly cache of the last 8 days. Filter by company name or number, postcode prefix, notice type and since date. Returns company, number, notice type, date, nature of business, liquidation type, postcode, notice link, the cache's dataTimestamp and any missing days; with a Companies House key on the deployment, up to 10 rows also get company status, incorporation date, SIC codes and address.",
    ["uk", "insolvency", "gazette", "companies house", "credit risk", "due diligence"], { since: "2026-10-01", q: "limited", type: "liquidators", limit: "50" },
    { properties: { since: { type: "string", description: "YYYY-MM-DD, default 7 days ago, clipped to the cache window" }, q: { type: "string", description: "Company name text or company number" }, postcode: { type: "string", description: "Postcode prefix, e.g. SW1 or M1 1AE" }, type: { type: "string", description: "administration, liquidation, winding-up, petition, creditors, or a notice name or 4-digit code" }, limit: { type: "string", description: "Max rows, 1-200, default 50" } } },
    { query: { since: "2026-10-01", until: "2026-10-07", q: "limited", postcode: null, type: "liquidators" }, returned: 1, total: 1, results: [{ company: "GLO LINK LIMITED", companyNumber: "11075587", noticeType: "Appointment of Liquidators", noticeCode: "2443", date: "2026-10-06", natureOfBusiness: "Other service activities not elsewhere classified", typeOfLiquidation: "Creditors Voluntary Liquidation", postcode: "MK13 7QW", noticeId: "5225502", link: "https://www.thegazette.co.uk/notice/5225502" }], dataTimestamp: "2026-10-06T21:33:05.005Z", coveredDays: ["2026-10-01", "2026-10-06"], missingDays: ["2026-10-07"], source: "The Gazette (Open Government Licence v3.0) via the SiteCheck gazette cache" }),
  "GET /api/read": tool("$0.002",
    "Read one web page as clean Markdown (or plain text) for an LLM: the main content without menus, cookie banners and footers, plus title, description, author, published date, language and canonical URL; links on request. robots.txt is respected (a disallowed page is refused and not charged). No JavaScript is run.",
    ["web scraping", "markdown", "reader", "llm", "rag", "web page"], { url: "https://docs.x402.org/introduction", format: "markdown", maxChars: "20000" },
    { properties: { url: { type: "string", description: "Page URL (http or https)" }, format: { type: "string", description: "markdown (default) or text" }, maxChars: { type: "string", description: "Cut the content at this many characters, 500-200000, default 30000" }, links: { type: "string", description: "1 = also return the page's links (up to 300)" }, images: { type: "string", description: "1 = keep images with alt text as Markdown images" } }, required: ["url"] },
    { url: "https://docs.x402.org/introduction", finalUrl: "https://docs.x402.org/introduction", status: 200, contentType: "text/html", title: "Welcome to x402 - x402", description: "x402 is an open payment standard...", author: null, publishedAt: null, lang: "en", canonical: "https://docs.x402.org/introduction", siteName: null, format: "markdown", content: "# Welcome to x402\n\nThis guide will help you understand x402...", chars: 5120, wordCount: 780, truncated: false, fetchedAt: "2026-10-08T18:00:00.000Z", note: "Fetched once, no JavaScript run; robots.txt respected. Content belongs to its publisher." }),
  "GET /api/email-check": tool("$0.001",
    "E-mail pre-check without SMTP: syntax, whether the domain can receive mail (MX or implicit MX, null MX, non-existent domain), disposable domain (9,000+ domain CC0 list), role account (info@, sales@...), free provider and a typo suggestion (gmial.com -> gmail.com). Verdict invalid / risky / unknown. Up to 50 addresses per call with emails=.",
    ["email", "validation", "email verification", "disposable email", "leads", "data quality"], { email: "john.smith@gmial.com" },
    { properties: { email: { type: "string", description: "One e-mail address" }, emails: { type: "string", description: "Alternative: up to 50 addresses, comma-separated" } } },
    { email: "john.smith@gmial.com", normalized: "john.smith@gmial.com", verdict: "risky", reasons: ["typo-suspected"], domain: "gmial.com", mx: true, mxHosts: ["mx.gmial.com"], disposable: false, role: false, freeProvider: false, suggestion: "john.smith@gmail.com", note: "No SMTP connection is made: 'unknown' means nothing is wrong with the address and its domain, not that the mailbox exists." }),
  "GET /api/domain": tool("$0.002",
    "Domain lookup over RDAP (the successor of WHOIS) and DNS: registered or available, registrar, creation, update and expiry dates, days until expiry, age, status codes, DNSSEC, name servers, plus whether it resolves (IPv4/IPv6) and its mail servers. Any TLD with an RDAP service; others are inferred from DNS.",
    ["domain", "whois", "rdap", "dns", "domain availability", "due diligence"], { domain: "wikipedia.org" },
    { properties: { domain: { type: "string", description: "Domain or URL, e.g. example.com or https://www.example.com/page" } }, required: ["domain"] },
    { domain: "wikipedia.org", registeredDomain: "wikipedia.org", registered: true, availability: "registered", rdapAvailable: true, registrar: "MarkMonitor Inc.", registrarIanaId: "292", createdAt: "2001-01-13T00:12:14.000Z", updatedAt: "2025-12-13T09:51:53.000Z", expiresAt: "2027-01-13T00:12:14.000Z", daysUntilExpiry: 461, ageDays: 9399, statusCodes: ["client delete prohibited", "client transfer prohibited"], dnssec: false, registrantCountry: "US", registrantOrganisation: "Wikimedia Foundation, Inc.", nameServers: ["ns0.wikimedia.org", "ns1.wikimedia.org"], dns: { resolves: true, ipv4: ["185.15.59.224"], ipv6: ["2a02:ec80:300:ed1a::1"], mx: ["mx-in1001.wikimedia.org"], nullMx: false }, note: "From the registry's RDAP service.", source: "IANA RDAP bootstrap + the TLD registry's RDAP server; DNS over HTTPS (Cloudflare, Google)" }),
  "GET /api/solana/token": tool("$0.002",
    "Solana token check for trading agents: price, market cap, FDV, liquidity, holders, 24h volume and trades, price change, organic-trading score, verification, top-holder and developer share (Jupiter), top pools (GeckoTerminal), plus on-chain mint authority, freeze authority, supply, decimals, token program and Token-2022 extensions, with red flags. Information only, not financial advice.",
    ["solana", "token", "crypto", "memecoin", "rug check", "defi", "trading"], { address: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263" },
    { properties: { address: { type: "string", description: "SPL token mint address (base58)" } }, required: ["address"] },
    { address: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263", name: "Bonk", symbol: "Bonk", priceUsd: 0.0000031741, marketCapUsd: 279305482.93, fdvUsd: 279305482.93, liquidityUsd: 5021663.2, holders: 1025725, volume24hUsd: 2010415.97, priceChangePct: { h1: -0.74, h24: -7.62 }, trades24h: { buys: 32350, sells: 33412, traders: 4936 }, organicScore: 92, organicScoreLabel: "high", verified: true, tags: ["verified", "meme"], tokenProgram: "spl-token", mintAuthorityEnabled: false, freezeAuthorityEnabled: false, topHoldersPercent: 30.57, devBalancePercent: 0, firstPoolCreatedAt: "2023-05-11T17:09:10.000Z", ageHours: 29151.5, url: "https://jup.ag/tokens/DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263", decimals: 5, supply: 87994365816957.88, mintAuthority: null, freezeAuthority: null, extensions: [], topPools: [{ pairAddress: "5zpyutJu9ee6jFymDGoK7F6S5Kczqtc9FomP3ueKuyA9", name: "Bonk / SOL", dex: "orca", liquidityUsd: 364954.54, volume24hUsd: 392457.69, priceUsd: 0.0000031, createdAt: "2023-07-05T14:41:09.000Z", url: "https://www.geckoterminal.com/solana/pools/5zpyutJu9ee6jFymDGoK7F6S5Kczqtc9FomP3ueKuyA9" }], flags: [], checks: { onchain: "ok", market: "jupiter", pools: "geckoterminal" }, disclaimer: "Information only, not financial advice." }),
  "GET /api/solana/trending": tool("$0.003",
    "Trending, newest, top-traded or top-organic Solana tokens (Jupiter) filtered by liquidity and 24h volume: price, market cap, liquidity, holders, volume, trades, price change, organic score, mint and freeze authority, top-holder share, age and red flags for each. Information only, not financial advice.",
    ["solana", "trending tokens", "new tokens", "memecoin", "trading", "crypto", "dex"], { mode: "trending", interval: "1h", minLiquidityUsd: "50000", limit: "10" },
    { properties: { mode: { type: "string", description: "trending (default), new, traded or organic" }, interval: { type: "string", description: "5m, 1h (default), 6h or 24h (not for new)" }, minLiquidityUsd: { type: "string", description: "Minimum liquidity in USD (default 50000; 5000 for new)" }, minVolume24hUsd: { type: "string", description: "Minimum 24h volume in USD" }, limit: { type: "string", description: "Max tokens, 1-100, default 20" } } },
    { mode: "trending", interval: "1h", filters: { minLiquidityUsd: 50000, minVolume24hUsd: 0 }, looked: 100, returned: 1, results: [{ address: "BPxxfRCXkUVhig4HS1Lh7kZqV6SPJhzfEk4x6fVBjPCy", name: "Backpack", symbol: "BP", priceUsd: 0.99711, marketCapUsd: 249277592.34, liquidityUsd: 334630.5, holders: 28081, volume24hUsd: 5120333.1, priceChangePct: { h1: 1.2, h24: 8.4 }, trades24h: { buys: 9120, sells: 8211, traders: 2210 }, organicScore: 88.1, organicScoreLabel: "high", verified: true, mintAuthorityEnabled: true, freezeAuthorityEnabled: true, topHoldersPercent: 80.2, ageHours: 41.5, flags: ["mint-authority-enabled: more tokens can be created", "freeze-authority-enabled: holders' tokens can be frozen", "concentrated: top holders own 80.2%"] }], disclaimer: "Information only, not financial advice.", source: "Jupiter token API (https://jup.ag)" }),
  "GET /api/tech": tool("$0.003",
    "Website technology detection: CMS, e-commerce platform, analytics, tag managers, CDN, hosting, chat, payments, A/B testing, consent tools and the e-mail provider, each with version, confidence 0-100 and evidence, from 231 own fingerprints over the home page, headers, cookies and the domain's MX/TXT records. For lead filtering and competitor research.",
    ["tech stack", "technology detection", "builtwith", "leads", "website", "competitor research"], { url: "shopify.com" }, urlSchema,
    { url: "https://shopify.com/", finalUrl: "https://www.shopify.com/", status: 200, domain: "shopify.com", cms: null, ecommerce: "Shopify", analytics: ["Google Analytics"], tagManagers: ["Google Tag Manager"], cdn: ["Cloudflare"], hosting: [], emailProvider: "Google Workspace", technologies: [{ name: "Shopify", category: "Ecommerce", version: null, confidence: 97, evidence: ["url https://cdn.shopify.com/s/files/..."] }], count: 14, blocked: null, note: "Home page markup, headers, cookies and DNS (MX, TXT) only; no JavaScript is run." }),
  "POST /api/pdf": tool("$0.003",
    "PDF to text: send an https link or base64 (up to 15 MB) and get the text page by page plus title, author, page count and dates. Text PDFs only: a scanned PDF without a text layer answers 422 and is not charged.",
    ["pdf", "pdf to text", "document", "extraction", "rag", "ocr-free"], { url: "https://bitcoin.org/bitcoin.pdf", maxChars: 20000 },
    { properties: { url: { type: "string", description: "http(s) link to a PDF" }, pdf_base64: { type: "string", description: "Alternative: the PDF as base64" }, maxChars: { type: "integer", description: "Cut the text at this many characters, 1000-500000, default 100000" } } },
    { pages: 9, title: null, author: null, subject: null, creator: "Writer", producer: "OpenOffice.org 2.4", createdAt: "2009-03-24T11:33:15Z", modifiedAt: null, chars: 21220, truncated: true, pagesReturned: 9, text: "Bitcoin: A Peer-to-Peer Electronic Cash System\nSatoshi Nakamoto...", byPage: [{ page: 1, text: "Bitcoin: A Peer-to-Peer Electronic Cash System..." }], note: "Text layer only, no OCR." }),
  "GET /api/fx": tool("$0.001",
    "Currency exchange rates from the European Central Bank (about 30 currencies, back to 1999): latest or a given date, amount conversion, or a daily time series between two dates. Source: ECB reference rates via Frankfurter.",
    ["exchange rates", "currency", "fx", "forex", "ecb", "conversion"], { from: "USD", to: "EUR,GBP,TRY", amount: "250" },
    { properties: { from: { type: "string", description: "Base currency, default USD" }, to: { type: "string", description: "Target currencies, comma-separated (default: all)" }, amount: { type: "string", description: "Amount to convert, default 1" }, date: { type: "string", description: "YYYY-MM-DD for a past day" }, start: { type: "string", description: "YYYY-MM-DD: time series start" }, end: { type: "string", description: "YYYY-MM-DD: time series end (default today)" } } },
    { base: "USD", amount: 250, date: "2026-10-08", rates: { EUR: 0.89397, GBP: 0.7612, TRY: 49.215 }, converted: { EUR: 223.4925, GBP: 190.3, TRY: 12303.75 }, source: "European Central Bank reference rates via Frankfurter (https://frankfurter.dev)" }),
  "GET /api/sitemap": tool("$0.002",
    "All URLs a website lists in its XML sitemaps (from robots.txt, /sitemap.xml or /sitemap_index.xml, following indexes), with lastmod, newest first. Filter by path prefix and changed-since date. For agents that need a site's page list before reading pages.",
    ["sitemap", "crawling", "seo", "urls", "website", "content discovery"], { url: "x402.org", limit: "100" },
    { properties: { url: { type: "string", description: "Site URL or domain" }, pathPrefix: { type: "string", description: "Only URLs whose path starts with this, e.g. /blog/" }, since: { type: "string", description: "YYYY-MM-DD: only URLs with lastmod on or after it" }, limit: { type: "string", description: "Max URLs, 1-10000, default 1000" } }, required: ["url"] },
    { site: "https://www.x402.org", sitemapsRead: 1, sitemaps: ["https://www.x402.org/sitemap.xml"], childSitemapsSkipped: 0, totalUrls: 2, returned: 2, truncated: false, urls: [{ url: "https://www.x402.org/writing/x402-v2-launch", lastmod: "2026-09-30" }, { url: "https://www.x402.org/", lastmod: null }] }),
  "GET /api/solana/wallet": tool("$0.003",
    "Solana wallet holdings: SOL and every SPL / Token-2022 balance with name, symbol, USD price and value (Jupiter), sorted by value, plus the total in USD. Dust and unpriced tokens hidden unless includeDust=1. Information only.",
    ["solana", "wallet", "portfolio", "balances", "crypto", "tokens"], { address: "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM" },
    { properties: { address: { type: "string", description: "Solana wallet address (base58)" }, includeDust: { type: "string", description: "1 = also list tokens worth under $0.01 or without a price" } }, required: ["address"] },
    { address: "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM", sol: { amount: 12.5, priceUsd: 106.49, valueUsd: 1331.1 }, totalValueUsd: 1581.1, tokenAccounts: 3, tokensShown: 1, hiddenDustOrUnpriced: 2, tokens: [{ mint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v", symbol: "USDC", name: "USD Coin", amount: 250, priceUsd: 1, valueUsd: 250, verified: true, program: "spl-token" }], disclaimer: "Information only, not financial advice." }),
  "POST /api/translate": tool("$0.002",
    "Translation with Llama 3.1 8B: up to 6,000 characters per call, formatting, names, numbers and URLs kept, source language detected when not given. Language codes like en, tr, de, fr, es, ar, zh, or language names.",
    ["translation", "translate", "languages", "localization", "ai", "llm"], { text: "Pay per call, no API key.", source: "en", target: "tr" },
    { properties: { text: { type: "string", description: "Up to 6000 chars" }, target: { type: "string", description: "Target language code or name, e.g. tr" }, source: { type: "string", description: "Optional source language; detected when omitted" } }, required: ["text", "target"] },
    { model: "@cf/meta/llama-3.1-8b-instruct-fast", source: "en", target: "tr", translated_text: "Çağrı başına ödeme, API anahtarı yok.", chunks: 1 }),
};

// Prediction markets, powered by the Panta API (lib/markets.js). Information only, not financial advice.
// build-buy returns an unsigned transaction; SiteCheck never signs, holds keys or custodies funds.
// POST /api/markets/report is free and not listed here (see lib/app.js).
const MARKET_ID = "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU";
const WALLET = "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM";
const orderSchema = {
  properties: {
    id: { type: "string", description: "Panta market id (the market's event address, base58), from GET /api/markets" },
    side: { type: "string", description: "yes or no" },
    amountUsdc: { type: "string", description: 'USDC to spend, as a decimal string, e.g. "5.00"' },
    wallet: { type: "string", description: "The buyer's Solana wallet (base58). It pays and signs; SiteCheck never does." },
  },
  required: ["id", "side", "amountUsdc", "wallet"],
};
const orderInput = { id: MARKET_ID, side: "yes", amountUsdc: "5.00", wallet: WALLET };

export const MARKET_CATALOG = {
  "GET /api/markets": tool("$0.002",
    "Search Panta prediction markets (USDC on Solana) by keywords, phase or category. Compact rows: question, YES/NO implied probability from live prices, volume, close and resolution times, resolution source. Powered by Panta. Information only, not financial advice.",
    ["prediction markets", "odds", "panta", "solana", "market data"], { q: "bitcoin", status: "primary", limit: "5" },
    { properties: { q: { type: "string", description: "Keywords, all must match (title, description, category)" }, status: { type: "string", description: "primary (open for buys), secondary, resolved or cancelled" }, category: { type: "string", description: "Optional: sports, crypto, politics, entertainment, finance, science, world, other" }, limit: { type: "string", description: "Max results, 1-20, default 10" } } },
    { total: 3, results: [{ id: MARKET_ID, question: "Will BTC close above $150k on 2026-12-31?", phase: "primary", priceUsdc: { yes: 0.31, no: 0.69 }, impliedProbability: { yes: 0.31, no: 0.69 }, volumeUsdc: 1200, closesAt: "2026-12-31T23:59:59.000Z", resolutionSource: "https://www.coingecko.com", buyable: true }], disclaimer: "Information only, not financial advice.", poweredBy: { text: "Powered by Panta", url: "https://panta.market" } }),
  "GET /api/markets/brief": tool("$0.01",
    "One Panta prediction market in depth: current YES/NO odds, recent trading activity and a short neutral AI summary of what it asks, what resolves it and what the price implies. No advice. Powered by Panta.",
    ["prediction markets", "odds", "panta", "research", "summary"], { id: MARKET_ID },
    { properties: { id: { type: "string", description: "Panta market id, from GET /api/markets" } }, required: ["id"] },
    { market: { id: MARKET_ID, question: "Will BTC close above $150k on 2026-12-31?", impliedProbability: { yes: 0.31, no: 0.69 } }, recentActivity: { sampled: 50, yesBuys: 31, noBuys: 19, last24h: 12 }, summary: { text: "This market asks whether...", source: "llm" }, disclaimer: "Information only, not financial advice." }),
  "POST /api/markets/quote": tool("$0.005",
    "Quote a YES or NO buy on a Panta market for a USDC amount and wallet: expected shares, average fill price, fee and price impact against the spot price. Nothing is signed or sent. Powered by Panta.",
    ["prediction markets", "quote", "panta", "solana", "trading"], orderInput, orderSchema,
    { expectedFill: { shares: 15.8, avgPrice: 0.3165, feeUsdc: 0.1 }, spotPrice: 0.31, priceImpact: 0.021, disclaimer: "Information only, not financial advice." }),
  "POST /api/markets/build-buy": tool("$0.01",
    "Build an unsigned Panta buy transaction (Solana v0, base64, plus the raw instructions) for your own wallet to sign and broadcast. SiteCheck never signs, holds keys or custodies funds. Then report the signature to POST /api/markets/report (free).",
    ["prediction markets", "unsigned transaction", "panta", "solana", "trading"], { ...orderInput, maxSlippageBps: 100 },
    { properties: { ...orderSchema.properties, maxSlippageBps: { type: "integer", description: "1-5000, default 100 (1%)" } }, required: orderSchema.required },
    { order: { orderId: "ord_...", quoteId: "qt_...", expectedShares: "15.80", feeUsdc: "0.10" }, transaction: { signed: false, format: "solana-v0", encoding: "base64", data: "AQAAAA...", feePayer: WALLET }, instructions: [{ programId: "...", data: "<base64>", accounts: [] }], disclaimer: "Information only, not financial advice." }),
};
